### ISSUE TITLE
Add a friendly error page

### ISSUE THREAD

**Issue by jonbiemond** [jonbiemond/BCIT-Flex#91]
Replace the default Flask error page.
Tutorial: https://realpython.com/flask-logging-messages/

Related #32

**Comment by abant07** [comment]
Hi!

Can I work on this. I am a bit new to Github, but I am interested in this, and I was just wondering in order to reproduce the environment, is there anything I should know other than following the ReadMe?

Thanks!

**Comment by jonbiemond** [comment]
Hi @abant07! Thanks for being interested in contributing, I've assigned you. Check out [CONTRIBUTING.md](https://github.com/jonbiemond/BCIT-Flex/blob/main/CONTRIBUTING.md) for some additional development setup steps. The main points are [forking the repo](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#forking-a-repository) and doing the work in a new branch. For this issue I don't think having the database is necessary, so you may try skipping that if you like.

**Comment by abant07** [comment]
Sounds good!

**Comment by abant07** [comment]
Hey do you know why I am getting import errors in the python files for like Flask and sqlalchemy. I had both of them preinstalled before I cloned the repo in VSCode.

I think that might be preventing me from starting up the web server. This is the error I get

[2024-01-28 11:04:18,375] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/amoghbantwal/Documents/GitHub/BCIT-Flex/bcitflex/course.py", line 33, in index
    DBSession.scalars(select(Program).where(Program.program_id.in_(program_ids)))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 1926, in scalars
    return self._proxied.scalars(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2420, in scalars
    return self._execute_internal(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2178, in _execute_internal
    bind = self.get_bind(**bind_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_sqlalchemy/session.py", line 53, in get_bind
    engines = self._db.engines
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 690, in engines
    raise RuntimeError(
RuntimeError: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?

**Comment by abant07** [comment]
Never mind, I was able to figure it out. I just had to change my python interpreter

**Comment by abant07** [comment]
I was able to get all the packages to work, but I still get that error when I flask --app bcitflex run

**Comment by abant07** [comment]
Also, I was curious to know, which file is the main .py file that is running the web server. Like the one with all the routes that redirect to certain html pages

And also, which file do I need to put a route to the error page? Is it the __init__.py file?

**Comment by jonbiemond** [comment]
Hey @abant07, can you confirm you are using `poetry` to install the dependencies? 

1. Clone your fork of the repo locally.
2. `poetry install`
3. `poetry run flask --app bcitflex run`

The app uses [Flask's factory pattern](https://flask.palletsprojects.com/en/3.0.x/patterns/appfactories/). `__ init__.py` is the entry point for the app. The routes are defined in their relative top level `.py` files, `course.py` for example. Likewise I think the route to the error page should also go in it's own file: `error.py`.

**Comment by abant07** [comment]
Yup I am using poetry, still getting this error

RuntimeError: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?

**Comment by jonbiemond** [comment]
Hey @abant07, I was able to replicate the error. It occurs when the app attempts to make a connection with the database. Unfortunately almost all pages of the site display data from the database, however some should still work. For example try [http://127.0.0.1:5000/account](http://127.0.0.1:5000/account) to get to the login page. To get the current default error page you can navigate to any invalid route, [http://127.0.0.1:5000/error](http://127.0.0.1:5000/error) for example.

**Comment by abant07** [comment]
Oh yes! You are right. I was able to get the /account page to load. Ok, then I will just create an error.py file, and create a errors.html file in the template folder and then route all 404 traffic errors to the /error page.

Thanks!

**Comment by abant07** [comment]
I also wanted to clarify, do I need to write any tests for this specific issue? If so, which file would it be in?

**Comment by jonbiemond** [comment]
Awesome! Yes, please add a test to confirm the new error page is being displayed. Please create a new file for the test: `tests/app/test_error.py`

**Comment by abant07** [comment]
I was able to finish a simple error page, with a test file, but when I tried to commit to my forked repo I got this error

alembic-check............................................................Failed
- hook id: alembic-check
- exit code: 1

Traceback (most recent call last):
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/alembic/config.py", line 630, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/alembic/config.py", line 624, in main
    self.run_cmd(cfg, options)
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/alembic/config.py", line 601, in run_cmd
    fn(
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/alembic/command.py", line 289, in check
    script_directory.run_env()
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/amoghbantwal/Documents/GitHub/BCIT-Flex/bcitflex/alembic/env.py", line 90, in <module>
    run_migrations_online()
  File "/Users/amoghbantwal/Documents/GitHub/BCIT-Flex/bcitflex/alembic/env.py", line 75, in run_migrations_online
    with connectable.connect() as connection:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 284, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amoghbantwal/Library/Caches/pypoetry/virtualenvs/bcitflex-Q0AGhald-py3.12/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by jonbiemond** [comment]
Hi @abant07, that's annoying, sorry. The Alembic hook expects a database and fails otherwise. I suggest running the lint, formatting and testing separately and skipping the pre-commit altogether. You can skip pre-commit by passing the `--no-verify` flag to the `git commit` command. For example:
```bash
git commit -m "my wonderful message" --no-verify
```

**Comment by abant07** [comment]
Alright sounds good. Will do.

Thanks

**Comment by abant07** [comment]
Ok looks good, I just submitted a PR

Thanks!
